# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  echo:
    docker: 
      image: circleci/python:3.7.3
        steps:
          - run:
            name: "Echo command"
            command: "print('echo')"
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - test echo:
        requires:
          welcome/run
  # Name the workflow "Echo"
     
      
      
